engines/cpl_concurrence/config/routes.rb
CplConcurrence::Engine.routes.draw do
  root 'notices#index'

  resources :notices,   path: 'editais'
  resources :passwords, path: 'minha-senha'
  resources :sessions,  path: 'acesso'
  resources :remembers, path: 'lembrar-senha'

  resources :users,    path: 'usuario' do 
    get 'confirmation_email', on: :collection, path: 'confirmacao-email'

    resources :notices, controller: :user_notices, path: 'editais'
    resources :notice_participations, controller: :user_notice_participations, path: 'edital-participacoes' do
      get 'session_participation', path: 'sessao'

      get 'proposal'
      get 'document'
      
      resources :documents, controller: :user_notice_documents
      resources :chats, controller: :user_notice_participation_chats
    end
  end

end

engines/cpl_concurrence/app/models/cpl_concurrence/application_record.rb
module CplConcurrence
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice.rb
module CplConcurrence
  class Notice < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notices'

    has_many :notice_users
    has_many :notice_chats
    has_many :notice_events

    def participation_open?
      (session_started_at >= Time.now) && (participation_ended_at < Time.now)
    end

  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice_chat.rb
module CplConcurrence
  class NoticeChat < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notice_chats'

    belongs_to :staff, class_name: "Core::Person::Staff"
    belongs_to :notice
    belongs_to :notice_user

  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice_event.rb
module CplConcurrence
  class NoticeEvent < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notice_events'

    belongs_to :staff, class_name: "Core::Person::Staff"
    belongs_to :notice
    belongs_to :notice_user

  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice_user.rb
module CplConcurrence
  class NoticeUser < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notice_users'

    belongs_to :notice
    belongs_to :user
    has_many   :user_documents, class_name: 'CplConcurrence::NoticeUserDocument', foreign_key: :notice_user_id
    
    validates_uniqueness_of :user_id, scope: :notice_id
  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice_user_credential.rb
module CplConcurrence
  class NoticeUserCredential < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notice_user_credentials'

    enum credential_type: ['proprietário_ou_sócio','procurador']
  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice_user_document.rb
module CplConcurrence
  class NoticeUserDocument < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notice_user_documents'

    validates :document, presence: true
    validates :document, file_size: { less_than_or_equal_to: 25.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png', 
                                                  'application/pdf','application/zip',
                                                  'application/x-rar-compressed',
                                                  'application/x-7z-compressed',
                                                  'application/vnd.ms-excel',
                                                  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                                                  'application/msword'
                                                 ] }

    mount_uploader :document, ::CplConcurrence::DocumentUploader

    after_commit :write_log
    
    
    private

    def write_log
      participation = CplConcurrence::NoticeUser.find_by(id: self.notice_user_id)
      notice = CplConcurrence::Notice.find_by(id: participation.notice_id)
      
      if self.deleted
        content = "Arquivo de proposta nº #{self.id} foi removido com uso de senha pessoal"
      else
        content = self.proposal? ? "Arquivo de proposta nº #{self.id} adicionado com uso de senha pessoal" : "Arquivo de documentação nº #{self.id} adicionado com uso de senha pessoal"
      end

      log = CplConcurrence::NoticeUserLog.new
      log.notice_id = notice.id
      log.user_id   = participation.user_id
      log.content   = content
      log.save
    end

  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/notice_user_log.rb
module CplConcurrence
  class NoticeUserLog < ActiveRecord::Base
    self.table_name = 'generic.cpl_concurrence_notice_user_logs'
    
  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/password.rb
module CplConcurrence
  class Password
    include ActiveModel::Model
  
    attr_accessor :current_password, :new_password, :confirmation_password, :user_id

    validates :current_password, :new_password, :confirmation_password, presence: true
    validate  :password_is_equal?

    def save
      return false if !valid?

      user = ::CplConcurrence::User.find_by(id: self.user_id)
      user.password = self.new_password
      user.save(validate: false)

      log = ::CplConcurrence::NoticeUserLog.new
      log.user_id = self.user_id
      log.content = "Senha alterada com uso da senha pessoal"
      log.save
      
      true 
    end

    private

    def password_is_equal?
      user = ::CplConcurrence::User.find_by(id: self.user_id)

      if self.current_password != user.password
        errors.add(:current_password, "não é igual ao cadastrado")
      end
      
      if self.new_password != self.confirmation_password
        errors.add(:new_password, "não é igual a confirmação")
      end
    end
  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/session.rb
module CplConcurrence
  class Session
    include ActiveModel::Model

    attr_accessor :cpf_cnpj, :password, :user_id

    validates :cpf_cnpj, cnpj: true, presence: true
    validates :password, presence: true
    validate  :authenticate
    
    def save
      return false if !valid?

      log = ::CplConcurrence::NoticeUserLog.new
      log.user_id = self.user_id
      log.content = "Acesso realizado com uso da senha pessoal"
      log.save
      
      true
    end

    private

    def authenticate
      user = ::CplConcurrence::User.find_by(cnpj: self.cpf_cnpj)

      if user.nil? || user.password != self.password
        errors.add(:cpf_cnpj, 'Dados informados não conferem')
      else
        self.user_id = user.id
      end
      
    end
    
  end
end

engines/cpl_concurrence/app/models/cpl_concurrence/user.rb
module CplConcurrence
  class User < ActiveRecord::Base 
    self.table_name = 'generic.cpl_concurrence_users'

    attr_accessor :email_confirmation, :password_confirmation

    validates :name, presence: true
    validates :cnpj, cnpj: true, presence: true, uniqueness: true
    validates :email, :email_confirmation, presence: true, email: true
    validates :password_confirmation, :password, length: { minimum: 6, maximum: 20}, presence: true

    validate  :password_equal
    validate  :email_equal

    private


    def password_equal
      if self.password != self.password_confirmation
        errors.add(:password_confirmation, 'não é igual a senha informada')
      end
    end
    
    def email_equal
      if self.email != self.email_confirmation
        errors.add(:email_confirmation, 'não é igual ao e-mail informado')
      end
    end
  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/application_controller.rb
require_dependency 'application_controller'

module CplConcurrence
  class ApplicationController < ApplicationController
    protect_from_forgery with: :exception
    after_action :set_iframe

    layout 'application'

    helper_method :current_notice_user, :authenticate_notice_user

    private

    def authenticate_notice_user
      if current_notice_user.nil? && controller_name != "sessions"
        redirect_to new_session_path
      end
    end


    def current_notice_user
      ::CplConcurrence::User.find_by(id: session[:user_notice_id])
    end

    def set_iframe
      response.headers["X-FRAME-OPTIONS"] = "ALLOWALL"
    end
  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/notice_sessions_controller.rb
module CplConcurrence
  class NoticeSessionsController < ApplicationController
    
    def show
    end 

  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/notices_controller.rb
require_dependency 'cpl_concurrence/application_controller'

module CplConcurrence
  class NoticesController < ApplicationController
    
    def index
    end 

    def show
    end 

    
  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/passwords_controller.rb
require_dependency 'cpl_concurrence/application_controller'

module CplConcurrence
  class PasswordsController < ApplicationController
    before_action :authenticate_notice_user

    def edit
      @user_password = CplConcurrence::Password.new(user_id: current_notice_user.id)
    end 
    
    def update
      @user_password = CplConcurrence::Password.new(set_params)
      @user_password.user_id = current_notice_user.id
      @user_password.save
    end 

    private

    def set_params
      params.require(:password)
        .permit(:new_password, :confirmation_password, :current_password)
    end 

  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/remembers_controller.rb
module CplConcurrence
  class RemembersController < ApplicationController

    def index
    end 

    def new
    end
    
    def edit
    end 

    def update
    end 



  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/sessions_controller.rb
require_dependency 'cpl_concurrence/application_controller'

module CplConcurrence
  class SessionsController < ApplicationController
    
    def index
      redirect_to action: :new
    end
    
    def new
      @session = CplConcurrence::Session.new
    end 
    
    def create
      @session = CplConcurrence::Session.new(set_params)

      if @session.save
        session[:user_notice_id] = @session.user_id
        redirect_to cpl_concurrence.user_notices_path(@session.user_id)
      else
        render action: :new
      end
    end 

    def destroy 
      session[:user_notice_id] = nil

      redirect_to cpl_concurrence.new_session_path
    end

    private

    def set_params
      params.require(:session).permit(:cpf_cnpj, :password)
    end

  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/user_notice_documents_controller.rb
require_dependency 'cpl_concurrence/application_controller'

module CplConcurrence
  class UserNoticeDocumentsController < ApplicationController
    before_action :authenticate_notice_user
    before_action :set_participation

    def create
      @user_document = CplConcurrence::NoticeUserDocument.where(notice_user_id: @participation.id).new(set_params)
      
      if @user_document.save
        flash[:success] = 'O Arquivo enviado com sucesso!' 
        redirect_to user_notice_participation_path(current_notice_user, @participation)
      else
        flash[:danger] = 'O Arquivo inválido, verifique o tamanho e tipo do arquivo enviado.' 
        redirect_to user_notice_participation_path(current_notice_user, @participation)
      end
    end 

    def index
      @user_document = CplConcurrence::NoticeUserDocument.where(notice_user_id: @participation.id).find_by(document: params[:id])
      
      if @user_document.nil?
        flash[:danger] = 'O Arquivo não encontrado'
        redirect_to user_notice_participation_path(current_notice_user, @participation)
      else
        send_file "#{Rails.root}/public#{@user_document.document_url}"
      end
      
    end
    
    def destroy 
      @user_document = CplConcurrence::NoticeUserDocument.where(notice_user_id: @participation.id).find_by(id: params[:id])
      @user_document.update(deleted: true, deleted_at: Time.now)

      flash[:success] = 'O Arquivo removido com sucesso!'
      redirect_to user_notice_participation_path(current_notice_user, @participation)
    end

    private

    def set_params
      params.require(:notice_user_document)
        .permit(:document,:proposal)
    end
    

    def set_participation
      @participation = CplConcurrence::NoticeUser.where(user_id: current_notice_user.id).find(params[:notice_participation_id])
    end

  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/user_notice_participation_chats_controller.rb
require_dependency 'cpl_concurrence/application_controller'

module CplConcurrence
  class UserNoticeParticipationChatsController < ApplicationController
    before_action :authenticate_notice_user
    
    def index
    end 
    
  end
end

engines/cpl_concurrence/app/controllers/cpl_concurrence/user_notice_participations_controller.rb
require_dependency 'cpl_concurrence/application_controller'

module CplConcurrence
  class UserNoticeParticipationsController < ApplicationController
    before_action :authenticate_notice_user
    
    def index
      @notices = CplConcurrence::NoticeUser.where(user_id: current_notice_user.id)
    end

    def show
      @participation = CplConcurrence::NoticeUser.where(user_id: current_notice_user.id).find(params[:id])
      @notice = CplConcurrence::Notice.find(@participation.notice_id)
      @logs = CplConcurrence::NoticeUserLog.where(user_id: current_notice_user.id, notice_id: @notice.id).order(created_at: :desc)
    end
    
    def session_participation
      @participation = CplConcurrence::NoticeUser.where(user_id: current_notice_user.id).find(params[:notice_participation_id])
      @notice = CplConcurrence::Notice.find(@participation.notice_id)
    end

    def proposal
    
    end 

    def document
    end


    def new
      @notice = CplConcurrence::NoticeUser.new(user_id: current_notice_user.id)
      @notice.notice_id = params[:notice_id]
      
      if @notice.save
        redirect_to user_notice_participation_path(current_notice_user, @notice.id)
      else
        flash[:danger] = 'Participação não disponível'
        redirect_to user_notices_path(current_notice_user)
      end
    end
  
  end 
end

engines/cpl_concurrence/app/views/cpl_concurrence/user_notice_participations/general.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        = render 'layouts/cpl_concurrence/header'
      .panel-body
        .row
          .col-md-12
            = render 'layouts/cpl_concurrence/tabs'
        .row
          .col-md-12
        .row
          .col-md-12
            .text-center
              = image_tag 'http://www.codhab.df.gov.br/portal/images/codhab.png', width: '300'
            = @notice.header_minute.html_safe

        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 8} PROPOSTAS
                %tr
                  %th Nº
                  %th CNPJ
                  %th Fornecedor
                  %th Porte ME/EPP
                  %th Declaração ME/EPP
                  %th Envelope 1
                  %th Envelope 2
                  %th Data/Hora
              %tbody
                - 10.times.each_with_index do |i|
                  %tr
                    %td= i + 1
                    %td 00.000.000/0000-00
                    %td Empresa exemplo #{i + 1}
                    %td Sim
                    %td Sim
                    %td= link_to "Visualizar", "#"
                    %td= link_to "Visualizar", "#"
                    %td 12/06/2018 05:35

        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} CLASSIFICAÇÃO
                %tr
                  %th #
                  %th CNPJ
                  %th Fornecedor
                  %th Porte ME/EPP
                  %th Valor
                  %th Data/Hora
              %tbody
                - 10.times.each_with_index do |i|
                  %tr
                    %td
                      %i Ainda não classificado
                    %td 00.000.000/0000-00
                    %td Empresa exemplo #{i + 1}
                    %td Sim
                    %td
                      %i Ainda não registrado
                    %td 12/06/2018 05:35

        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} EVENTOS
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                %tr
                  %td.collapsing 12/06/2019 - 08:02        
                  %td.collapsing Nome usuário        
                  %td Abertura de sessão realizada através de senha pessoal     
                %tr
                  %td.collapsing 12/06/2019 - 08:03       
                  %td.collapsing Nome usuário        
                  %td Visualização de envelope 1 da participação vínculada ao CPNJ 00.000.000/0000-00     
                %tr
                  %td.collapsing 12/06/2019 - 08:04        
                  %td.collapsing Nome usuário        
                  %td Visualização de envelope 2 da participação vínculada ao CPNJ 00.000.000/0000-00     
                %tr
                  %td.collapsing 12/06/2019 - 08:05        
                  %td.collapsing Nome usuário        
                  %td Inserção de valor de proposta enviado pelo CNPJ 00.000.000/0000-00  
        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} CHAT
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                - 2.times.each_with_index do |i|
                  %tr
                    %td.collapsing 12/06/2019 08:0#{i}                              
                    %td.collapsing Usuário extranet                              
                    %td Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at ipsum neque. Suspendisse a mi eget dui ultricies vulputate. Nam efficitur elit non scelerisque varius. Sed eu commodo leo. Maecenas at enim ante. Vivamus nulla erat, feugiat a lacinia quis, pulvinar in turpis. Nulla ornare aliquet fermentum. Praesent faucibus fringilla nisl, vitae dignissim sapien dictum id. Sed aliquam nisi suscipit leo pulvinar bibendum. Nullam auctor magna est. Proin dapibus dolor id risus pulvinar, sed tincidunt dui blandit.                              
                            
        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} AVISOS
              %tbody
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                %tr
                  %td{colspan: 3}
                    Nenhum aviso registrado.
        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} RECURSOS
              %tbody
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                %tr
                  %td{colspan: 3}
                    Nenhum recurso registrado.          

engines/cpl_concurrence/app/views/cpl_concurrence/user_notice_participations/index.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        = render 'layouts/cpl_concurrence/header'
      .panel-body
        .row
          .col-md-12
            = render 'layouts/cpl_concurrence/tabs'
        .row
          .col-md-12
            %table.table.table-striped.table-celled.table-bordered
              %thead
                %tr
                  %th Número
                  %th Edital
                  %th.collapsing Limite para participação
                  %th.collapsing Abertura da sessão
                  %th

              %tbody
                - @notices.each do |user_notice|
                  %tr
                    %td.collapsing= user_notice.notice.number
                    %td= user_notice.notice.title
                    %td.collapsing
                      #{user_notice.notice.session_start_date.strftime("%d/%m/%Y")} - #{user_notice.notice.session_start_hour.strftime("%H:%M")}
                    %td.collapsing
                      #{user_notice.notice.session_start_date.strftime("%d/%m/%Y")} - #{user_notice.notice.session_start_hour.strftime("%H:%M")}
                    %td.collapsing
                      

engines/cpl_concurrence/app/views/cpl_concurrence/user_notice_participations/session_participation.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        = render 'layouts/cpl_concurrence/header'
      .panel-body
        .row
          .col-md-12
            = render 'layouts/cpl_concurrence/tabs'
        .row
          .col-md-12
        .row
          .col-md-12
            .text-center
              = image_tag 'http://www.codhab.df.gov.br/portal/images/codhab.png', width: '300'
            = @notice.header_minute.html_safe

        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 8} PROPOSTAS
                %tr
                  %th Nº
                  %th CNPJ
                  %th Fornecedor
                  %th Porte ME/EPP
                  %th Declaração ME/EPP
                  %th Envelope 1
                  %th Envelope 2
                  %th Data/Hora
              %tbody
                - @notice.notice_users.order(created_at: :asc).each_with_index do |notice_user, index|
                  %tr
                    %td= index + 1
                    %td= notice_user.user.cnpj rescue nil
                    %td= notice_user.user.name rescue nil
                    %td
                    %td
                    %td= link_to "Visualizar", user_notice_participation_document_path(@notice, notice_user)
                    %td= link_to "Visualizar", user_notice_participation_proposal_path(@notice  )
                    %td= notice_user.created_at.strftime("%d/%m/%Y %H:%M")

        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} CLASSIFICAÇÃO
                %tr
                  %th #
                  %th CNPJ
                  %th Fornecedor
                  %th Porte ME/EPP
                  %th Valor
                  %th Data/Hora
              %tbody
                - @notice.notice_users.order(created_at: :asc).each_with_index do |notice_user, index|
                  %tr
                    %td 
                      - if notice_user.value.nil?
                        %i Ainda não classificado 
                      - else
                        = index + 1 
                    %td= notice_user.user.cnpj rescue nil
                    %td= notice_user.user.name rescue nil
                    %td
                    %td
                      - if notice_user.value.nil?
                        %i Ainda não informado
                      - else
                        = number_to_currency notice_user.value
                    %td= notice_user.created_at.strftime("%d/%m/%Y %H:%M")
        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} EVENTOS
                %tr
                  %th.collapsing Data/Hora
                  %th Descrição
                  %th Autor
                  %th.collapsing Participante (CNPJ)
              %tbody
                - @notice.notice_events.order(created_at: :desc).each do |notice_event|
                  %tr
                    %td.collapsing= notice_event.created_at.strftime("%d/%m/%Y %H:%M")       
                    %td.collapsing= notice_event.description.upcase       
                    %td= notice_event.staff.name.upcase rescue 'sem informação'  
                    %td.collapsing= notice_event.notice_user.user.cnpj rescue 'sem informação'  

        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} CHAT
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                - @notice.notice_chats.order(created_at: :asc).each do |notice_chat|
                  %tr
                    %td.collapsing= notice_chat.created_at.strftime("%d/%m/%Y %H:%M")                            
                    %td.collapsing= notice_chat.staff.name.upcase rescue "Sem informação"                              
                    %td= notice_chat.content     
        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} AVISOS
              %tbody
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                %tr
                  %td{colspan: 3}
                    Nenhum aviso registrado.
        .row
          .col-md-12
            %table.table.table-striped.table-celled
              %thead
                %tr
                  %th.th-gray.text-center{colspan: 6} RECURSOS
              %tbody
                %tr
                  %th.collapsing Data/Hora
                  %th Autor
                  %th Descrição
              %tbody
                %tr
                  %td{colspan: 3}
                    Nenhum recurso registrado.          


:javascript
  setTimeout(function() {
    location = ''
  }, 20000);

engines/cpl_concurrence/app/views/cpl_concurrence/user_notice_participations/show.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        = render 'layouts/cpl_concurrence/header'
      .panel-body
        .row
          .col-md-12
            = render 'layouts/cpl_concurrence/tabs'
        .row
          .col-md-12
            %table.table.table-striped.table-bordered.table-celled
              %thead
                %tr
                  %th Número
                  %th Edital
                  %th.collapsing Participação iniciada em
              %tbody
                %tr
                  %td.collapsing= @notice.number
                  %td= @notice.title
                  %td= @participation.created_at.strftime("%d/%m/%Y - %H:%M")
        %br/
        .row
          .col-md-6
            = link_to "Voltar para minhas participações", user_notice_participations_path(current_notice_user), class: 'btn btn-primary'
          .col-md-6{style: 'text-align: right'}
            = link_to "Entrar no chat", user_notice_participation_chats_path(current_notice_user, @participation), class: 'btn btn-success', remote: true
                          
        .row
          .col-md-12
            %table.table.table-striped.table-bordered.table-celled
              %thead
                %tr
                  %th.collapsing.text-center 
                    %h3 
                      %b CREDENCIAMENTO
              %tbody  
                %tr
                  %td
                    = render 'cpl_concurrence/notice_user_credentials/form'

        .row
          .col-md-12
            %table.table.table-striped.table-bordered.table-celled
              %thead
                %tr
                  %th.collapsing.text-center 
                    %h3 
                      %b Data/Hora para início da sessão
              %tbody
                %tr
                  %td.collapsing.text-center
                    %h4
                      %b= @notice.session_started_at.strftime("%d/%m/%Y")
        .row
          .col-md-6                          
            %table.table.table-striped.table-bordered.table-celled
              %thead
                %tr
                  %th.collapsing.text-center 
                    %h3
                      %b 
                        ENVELOPE N° 01 
                        %br/
                        PROPOSTA DE PREÇOS
                    COMPANHIA DE DESENVOLVIMENTO HABITACIONAL DO DF - CODHAB
                    %br/
                    CONCORRÊNCIA Nº #{@notice.number}
                    %br/
                    = current_notice_user.name
                    %br/
                    = current_notice_user.cnpj.format_cnpj
                    %br/
                    Finaliza em #{@notice.participation_ended_at.strftime("%d/%m/%Y")} 
              %tbody
                %tr                            
                  %td.form-proposal
                    = render 'cpl_concurrence/user_documents/proposal_index'

          .col-md-6
            %table.table.table-striped.table-bordered.table-celled
              %thead
                %tr
                  %th.collapsing.text-center 
                    %h3
                      %b 
                        ENVELOPE N° 02 
                        %br/ 
                        DOCUMENTOS DE HABILITAÇÃO
                    COMPANHIA DE DESENVOLVIMENTO HABITACIONAL DO DF - CODHAB
                    %br/
                    CONCORRÊNCIA Nº #{@notice.number}
                    %br/
                    = current_notice_user.name
                    %br/
                    = current_notice_user.cnpj.format_cnpj
                    %br/
                    Finaliza em #{@notice.participation_ended_at.strftime("%d/%m/%Y")}
              %tbody
                %tr
                  %td.form-proposal
                    = render 'cpl_concurrence/user_documents/document_index'
                    
                

          .col-md-2                            

        .row
          .col-md-12
            %table.table.table-striped.table-celled.table-bordered
              %thead
                %tr
                  %th.text-center{colspan: 2} 
                    %h4
                      %b Histórico de atividades
                %tr
                  %th Data/Hora
                  %th Descrição
              %tbody
                - if @logs.present?
                  - @logs.each do |log|
                    %tr
                      %td.collapsing= log.created_at.strftime("%d/%m/%Y %H:%M")
                      %td= log.content
                - else 
                  %tr
                    %td{colspan: 2}
                      Nenhuma atividade realizada.