engines/attendance/config/routes.rb
Attendance::Engine.routes.draw do

  root 'cadastres#index'

  resources :profiles, only: [:edit, :update]
  
  resources :remember_passwords
  resources :cadastres do
    collection do
      get 'detail',       to: 'cadastres#detail'
      get 'pontuation',   to: 'cadastres#pontuation'
      get 'dependent',    to: 'cadastres#dependent'
      get 'occurrence',   to: 'cadastres#occurrence'
      get 'entity',       to: 'cadastres#entity'
      get 'situation',    to: 'cadastres#situation'
      get 'address',      to: 'cadastres#address'
      get 'schedule',     to: 'cadastres#schedule'
      get 'document',     to: 'cadastres#document'
      get 'indication',   to: 'cadastres#indication'
    end
  end
  
  resources :sessions, only: [:new, :create] do
    delete 'logout', to: 'sessions#destroy', on: :collection
  end
  resources :notifications

  resources :tickets do

    get '/confirm/:action_id',          to: 'tickets#confirm',          as: :confirm
    get '/open/:action_id',             to: 'tickets#open',             as: :open
    get '/close',                       to: 'tickets#close',            as: :close
    get '/close_action/:action_id',     to: 'tickets#close_action',     as: :close_action
    get '/close_dependent/:action_id',  to: 'tickets#close_dependent',  as: :close_dependent

    get '/update_cadastre',  to: 'tickets#update_cadastre',   as: :update_cadastre
    get '/update_dependent', to: 'tickets#update_dependent',  as: :update_dependent
    get '/update_income',    to: 'tickets#update_income',     as: :update_income
    get '/update_contact',   to: 'tickets#update_contact',    as: :update_contact

    get '/continue_cadastre/:action_id',  to: 'tickets#continue_cadastre',   as: :continue_cadastre
    get '/continue_dependent/:action_id', to: 'tickets#continue_dependent',  as: :continue_dependent
    get '/continue_income/:action_id',    to: 'tickets#continue_income',     as: :continue_income
    get '/continue_contact/:action_id',   to: 'tickets#continue_contact',    as: :continue_contact

    resources :cadastres
    resources :dependents
    resources :incomes
    resources :contacts

    resources :action, only: nil do
      resources :documents
    end

  end

  #resources :chats do
  #  resources :chat_comments
  #end

  resources :requeriments
  resources :schedules

  resources :external_requeriments
end

engines/attendance/app/models/attendance/application_record.rb
module Attendance
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/attendance/app/controllers/attendance/application_controller.rb
require_dependency 'application_helper'
require_dependency 'application_controller'

module Attendance
  class ApplicationController < ApplicationController
    protect_from_forgery with: :exception
    #before_action :urgent_redirect

    helper ApplicationHelper

    layout 'attendance'

    helper_method :authenticate_cadastre!
    helper_method :current_cadastre


    private

    def urgent_redirect
      redirect_to attendance.new_session_path if controller_name != 'sessions'
    end


    def authenticate_cadastre!
      if !current_cadastre.present?
        redirect_to attendance.new_session_path
      end
    end

    def current_cadastre
      @cadastre = Core::Candidate::Cadastre.find(session[:current_cadastre_id]) rescue nil

      return nil if @cadastre.nil?

      @cadastre = Core::Candidate::CadastrePresenter.new(@cadastre) rescue nil
      @cadastre = Core::Attendance::CadastrePresenter.new(@cadastre) rescue nil
      @cadastre = Core::Attendance::CadastrePolicy.new(@cadastre) rescue nil
    end

  end
end

engines/attendance/app/controllers/attendance/cadastres_controller.rb
module Attendance
  class CadastresController < ApplicationController

    before_action :authenticate_cadastre!
    before_action :set_ticket, only: [:edit, :update]
    before_action :set_action, only: [:edit, :update]
    before_action :set_cadastre, only: [:edit, :update]
    before_action :set_cadastre_mirror, only: [:edit, :update]

    def index
      session[:context_id] = nil 
    end

    def edit
      @cadastre_mirror = Core::Attendance::CadastreForm.find(@cadastre_mirror.id)
    end

    def update
      @cadastre_mirror = Core::Attendance::CadastreForm.find(@cadastre_mirror.id)

      if @cadastre_mirror.update(set_params)
        redirect_to ticket_continue_cadastre_path(@ticket, @action)
      else
        render action: :edit
      end
    end

    def detail
      @cadastre = current_cadastre
    end

    def dependent
      @dependents = current_cadastre.dependents.where('kinship_id <> 6')
      @spouse = current_cadastre.dependents.where(kinship_id: 6).first
    end

    def pontuation
      @pontuations = current_cadastre.pontuations
    end

    def entity
      @entity = current_cadastre.old_candidates.last
    end

    def situation
      @situations = current_cadastre.cadastre_situations
    end

    def schedule
      @schedules = current_cadastre.schedules
    end

    def document
      @documents = current_cadastre.assessments
    end

    def address
      @address = current_cadastre.presenter.current_cadastre_address
    end

    def occurrence
      @iptus = current_cadastre.iptus
    end

    def indication
      @indications = current_cadastre.enterprise_cadastres
    end

    private

    def set_params
      params.require(:attendance_cadastre_form)
            .permit(:rg, :rg_org, :gender, :born, :born_uf,
                    :rg_uf, :place_birth, :mother_name, :special_condition_id,
                    :special_condition_type_id, :nis, :cid, :adapted_property,
                    :arrival_df)
    end

    def set_ticket
      @ticket = @cadastre.tickets.find(params[:ticket_id])
      @ticket = Core::Attendance::TicketPolicy.new(@ticket)
    end

    def set_action
      @action = @ticket.actions.find_by(context_id: 1)
    end

    def set_cadastre
      @cadastre = current_cadastre
    end

    def set_cadastre_mirror
      @cadastre_mirror = @cadastre.cadastre_mirrors.find(@ticket.cadastre_mirror_id)
    end

  end
end

engines/attendance/app/controllers/attendance/chat_comments_controller.rb
module Attendance
  class ChatCommentsController < ApplicationController

    before_action :set_chat

    def new
      # @chat_comment = @chat.chat_comments.new
    end

    def create
      #@chat_comment = @chat.chat_comments.new(set_params)
      #if @chat_comment.save
      #  @service = Core::Attendance::ChatCommentService.new(@chat, @chat_comment, nil)
      #  @service.candidate_notification!
      # redirect_to chats_path
      #else
      # render :new
      # end
    end

    private

      def set_params
        params.require(:attendance_chat_comment).permit(:content, chat_uploads_attributes: [:document, :id])
      end

      def set_chat
        #@chat = current_cadastre.attendance_chats.find(params[:chat_id])
      end

  end
end

engines/attendance/app/controllers/attendance/chats_controller.rb
require_dependency 'attendance/application_controller'

module Attendance
  class ChatsController < ApplicationController

    def index
      #@chats = current_cadastre.attendance_chats
      #@chats = Core::Attendance::ChatPolicy.new(@chats)
    end

    def new
     #@chat = current_cadastre.attendance_chats.new
     #@chat.chat_comments.build
    end

    def create
      #@chat = current_cadastre.attendance_chats.new(set_params)
      #if @chat.save
      #  redirect_to new_chat_chat_comment_path(@chat)
      #else
      #  render :new
      #end
    end

    def show
      #@chat = current_cadastre.attendance_chats.find(params[:id])
      #@chat = Core::Attendance::ChatPolicy.new(@chat)
      #@service = Core::Attendance::ChatCommentService.new(nil, nil, @chat.chat_comments)
      #@service.reading_comment!
    end

    private

    def set_params
      params.require(:attendance_chat).permit(:chat_category_id)
    end


  end
end

engines/attendance/app/controllers/attendance/contacts_controller.rb
module Attendance
  class ContactsController < ApplicationController

    before_action :set_cadastre 
    before_action :set_ticket
    before_action :set_action
    before_action :set_cadastre_mirror 

    def edit
      @cadastre_mirror = Core::Attendance::ContactForm.find(@cadastre_mirror.id)
    end

    def update
      @cadastre_mirror = Core::Attendance::ContactForm.find(@cadastre_mirror .id)

      if @cadastre_mirror.update(set_params)
        redirect_to ticket_continue_contact_path(@ticket, @action)
      else
        render action: :edit
      end
    end

    private

    def set_params
      params.require(:attendance_contact_form)
            .permit(:telephone, :telephone_optional, :celphone, :email, :address, :city_id, :cep)
    end

    def set_ticket
      @ticket = @cadastre.tickets.find(params[:ticket_id])
      @ticket = Core::Attendance::TicketPolicy.new(@ticket)
    end

    def set_action
      @action = @ticket.actions.find_by(context_id: 4)
    end

    def set_cadastre
      @cadastre = current_cadastre
    end

    def set_cadastre_mirror
      @cadastre_mirror = @cadastre.cadastre_mirrors.find(@ticket.cadastre_mirror_id)
    end
  end
end

engines/attendance/app/controllers/attendance/dependents_controller.rb
require_dependency 'attendance/application_controller'

module Attendance
  class DependentsController < ApplicationController

    before_action :set_cadastre 
    before_action :set_ticket
    before_action :set_cadastre_mirror
    before_action :set_action
    before_action :set_dependent_mirror, only: [:edit, :update, :show, :destroy]

    def index
      @cadastre_mirror = Core::Attendance::CadastreForm.find(@cadastre_mirror.id)
    end

    def show
      @dependent_mirror = Core::Attendance::DependentForm.find(@dependent_mirror.id)
    end

    def new
      @dependent_mirror = Core::Attendance::DependentForm.new
    end

    def create
      @dependent_mirror = Core::Attendance::DependentForm.new(set_params)
      
      if @dependent_mirror.valid?
        @new_dependent_mirror = @cadastre_mirror.dependent_mirrors.new(@dependent_mirror.attributes)
        @new_dependent_mirror.save
          
        redirect_to ticket_continue_dependent_path(@ticket, @action, dependent_id: @new_dependent_mirror.id)
      else
        render action: :new
      end
    end

    def edit
      @dependent_mirror = Core::Attendance::DependentForm.find(@dependent_mirror.id)
    end

    def update
      @dependent_mirror = Core::Attendance::DependentForm.find(@dependent_mirror.id)
      
      if @dependent_mirror.update(set_params)
        session[:dependent_id] = @dependent_mirror.id
        redirect_to ticket_continue_dependent_path(@ticket, @action, dependent_id: @dependent_mirror.id)
      else
        render action: :edit
      end
    end

    def destroy
      @dependent_mirror.destroy

      redirect_to ticket_dependents_path(@ticket)
    end

    private

    def set_params
      params.require(:attendance_dependent_form)
            .permit(:rg, :name, :cpf, :rg_org, 
                    :income, :born, :kinship_id, 
                    :special_condition_id, :cid,
                    :special_condition_type_id)
    end

    def set_dependent_mirror
      @dependent_mirror = @cadastre_mirror.dependent_mirrors.find(params[:id])
    end

    def set_ticket
      @ticket = @cadastre.tickets.find(params[:ticket_id])
      @ticket = Core::Attendance::TicketPolicy.new(@ticket)
    end

    def set_action
      @action = @ticket.actions.find_by(context_id: 2)
    end

    def set_cadastre
      @cadastre = current_cadastre
    end

    def set_cadastre_mirror
      @cadastre_mirror = @cadastre.cadastre_mirrors.find(@ticket.cadastre_mirror_id)
    end
  end
end

engines/attendance/app/controllers/attendance/documents_controller.rb
require_dependency 'attendance/application_controller'

module Attendance
  class DocumentsController < ApplicationController
      
    before_action :set_cadastre
    before_action :set_ticket
    before_action :set_action 


    def new      
      params[:dependent_id] ||= nil

      @action   = Core::Attendance::ActionDocumentForm.find(@action.id)
      @action   = Core::Attendance::ActionPolicy.new(@action)

      @service  = Core::Attendance::DocumentService.new({cadastre: @cadastre,
                                                         action: @action,
                                                         ticket: @ticket,
                                                         dependent_id: params[:dependent_id]})

      @service.documents_required!

      @action = @service.action
    end

    def create

      if @action.update(set_params)
        
        if @action.context_id == 2
          redirect_to ticket_dependents_path(@ticket)
        elsif @action.context_id == 3
          redirect_to ticket_incomes_path(@ticket)
        else
          @service = Core::Attendance::TicketService.new(cadastre: @cadastre, ticket: @ticket, action: @action)
          @service.close_action

          redirect_to new_ticket_path
        end
      else
        render action: :new
      end

    end

    private

    def set_params
      params.fetch(:attendance_action_document_form, {})
            .permit(
              born_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              certificate_born_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              income_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              rg_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              cpf_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              residence_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              arrival_df_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              registry_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              payment_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              income_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model],
              special_condition_documents_attributes: [:id, :_destroy, :document, :target_id, :target_model]
              )
    end

    def set_cadastre
      @cadastre = current_cadastre
    end

    def set_ticket
      @ticket   = @cadastre.tickets.find(params[:ticket_id]).policy
    end

    def set_action
      @action   = @ticket.actions.find(params[:action_id])
    end
  end
end

engines/attendance/app/controllers/attendance/incomes_controller.rb
module Attendance
  class IncomesController < ApplicationController

    before_action :set_cadastre 
    before_action :set_ticket
    before_action :set_cadastre_mirror
    before_action :set_action

    def index
    end

    def edit
      @dependent = params[:dependent]
      
      if @dependent.present?
        @mirror = Core::Attendance::IncomeDependentForm.find(params[:id]) rescue nil
      else
        @mirror = Core::Attendance::IncomeForm.find(params[:id]) rescue nil
      end
    end

    def update
      @dependent_params = params[:dependent]

      if @dependent_params.present?
        @cadastre_mirror = Core::Attendance::IncomeDependentForm.find(params[:id]) rescue nil

        if @cadastre_mirror.update(set_dependent_params)
          redirect_to ticket_continue_income_path(@ticket, @action, dependent_id: @cadastre_mirror.id)
        else
          render action: :edit
        end
      else
        @cadastre_mirror = Core::Attendance::IncomeForm.find(params[:id]) rescue nil
        
        if @cadastre_mirror.update(set_params)
          redirect_to ticket_continue_income_path(@ticket, @action)
        else
          render action: :edit
        end
      end
      
    end


    private

    def set_params
      params.require(:attendance_income_form).permit(:main_income, :income)
    end
    
    def set_dependent_params
      params.require(:attendance_income_dependent_form).permit(:income)
    end

    def set_ticket
      @ticket = @cadastre.tickets.find(params[:ticket_id])
      @ticket = Core::Attendance::TicketPolicy.new(@ticket)
    end

    def set_action
      @action = @ticket.actions.find_by(context_id: 3)
    end

    def set_cadastre
      @cadastre = current_cadastre
    end

    def set_cadastre_mirror
      @cadastre_mirror = @cadastre.cadastre_mirrors.find(@ticket.cadastre_mirror_id)
    end

  end
end

engines/attendance/app/helpers/attendance/application_helper.rb
module Attendance
  module ApplicationHelper
    def link_to_add_fields(name, f, association)
      new_object = f.object.send(association).klass.new
      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|
        render(association.to_s.singularize + "_fields", f: builder)
      end
      link_to("<i class='plus icon'></i> Adicionar arquivo".html_safe, '#', class: "add_fields btn btn-primary icon mini", data: {id: id, fields: fields.gsub("\n", "")})
    end

    def link_to_add_upload_fields(name, f, association, target_id = nil, target_model = nil, persisted = nil)
      if target_id.nil?
        new_object = f.object.send(association).new
      else 
        new_object = f.object.send(association).where(target_id: target_id, target_model: target_model).new
      end

      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|
        render('document_fields', f: builder)
      end

      class_disabled = persisted ? '' : 'disabled'

      link_to("Adicionar arquivo".html_safe, '#', class: "add_fields #{class_disabled}", data: {id: id, fields: fields.gsub("\n", "")})
    end

  end
end

engines/attendance/app/views/attendance/cadastres/_form.html.haml
= simple_form_for @cadastre_mirror, url: @ticket.input_disabled?(@action) ? "#" : ticket_cadastre_path(@ticket, @cadastre_mirror), validate: true do |f|
  = f.input :name, input_html: { disabled: true }
  = f.input :cpf, input_html: { class: 'cpf', disabled: true }
  .row
    .col-md-4
      = f.input :gender, as: :select, include_blank: 'false', collection: Core::Candidate::Cadastre.genders.keys, input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-4
      = f.input :born, as: :string, input_html: { class: 'date', disabled: @ticket.input_disabled?(@action), value: f.object.born.present? ? localize(f.object.born) : nil}
    .col-md-4
      = f.input :born_uf, as: :select, include_blank: false, collection: Core::Address::State.all.order(:acronym), label_method: :acronym, value_method: :acronym, input_html: { disabled: @ticket.input_disabled?(@action) }
  .row
    .col-md-4
      = f.input :rg, input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-4
      = f.input :rg_org, input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-4
      = f.input :rg_uf, as: :select, include_blank: false, collection: Core::Address::State.all.order(:acronym), label_method: :acronym, value_method: :acronym, input_html: { disabled: @ticket.input_disabled?(@action) }
  .row
    .col-md-8
      = f.input :place_birth, input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-4
      = f.input :arrival_df, as: :string, include_blank: false, input_html: { disabled: @ticket.input_disabled?(@action) , class: 'date', value: f.object.arrival_df.present? ? localize(f.object.arrival_df) : nil}
  
  = f.input :mother_name, input_html: { disabled: @ticket.input_disabled?(@action) }
  .row
    .col-md-3
      = f.association :special_condition, as: :select, include_blank: false, input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-3
      = f.association :special_condition_type, as: :select, include_blank: "Nenhuma", input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-3
      = f.input :nis, input_html: { disabled: @ticket.input_disabled?(@action) }
    .col-md-3
      = f.input :cid, input_html: { disabled: @ticket.input_disabled?(@action) }
  .row
    .col-md-3
      = f.input :adapted_property, as: :select, include_blank: false, input_html: { disabled: @ticket.input_disabled?(@action) }
  .mini-margin
  .row
    .col-md-12
      - if @ticket.confirmation_required?(@action)
        .row
          .col-md-3
            = link_to "Meus dados estão corretos", ticket_confirm_path(@ticket, @action), class: 'btn btn-success', data: { disable_with: t(:disable_with)}
          .col-md-3
            = link_to "Atualizar meus dados", ticket_open_path(@ticket, @action), class: 'btn btn-warning', data: { disable_with: t(:disable_with)}
      - elsif @ticket.open?(@action)
        .divider
        = f.submit "Salvar dados", class: "btn btn-success", data: { disable_with: t(:disable_with)}
      - else
        .row
          .col-md-3
            = link_to "Corrigir minha atualização", ticket_open_path(@ticket, @action), class: 'btn btn-warning'
          .col-md-3
            = link_to "Corrigir documentação", new_ticket_action_document_path(ticket_id: @ticket, action_id: @action), class: 'btn btn-primary'
          .col-md-3
            = link_to "Voltar para atualizações", new_ticket_path, class: 'btn btn-default'

engines/attendance/app/views/attendance/cadastres/address.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            %h4
              %b
                Endereço Vinculado
        .row
          .col-md-12
            - if @address.present?
              %table.table.table-striped.table-bordered
                %thead
                  %tr
                    %th Cidade
                    %th Endereço
                %tbody
                  %tr
                    %td= @address.unit.city.name rescue nil
                    %td= @address.unit.complete_address rescue nil
                %thead
                  %tr
                    %th Situação
                    %th Data
                %tbody
                  %tr
                    %td= @address.situation_id.mb_chars.upcase  rescue nil
                    %td= @address.created_at.strftime('%d/%m/%Y') rescue nil
            - else
              %i Candidato não tem vínculo com endereço.

engines/attendance/app/views/attendance/cadastres/dependent.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            %h4
              %b
                Meus Dependentes
        .row
          .col-md-12
            - if @spouse.present?
              %table.table.table-striped.table-bordered
                %thead
                  %tr
                    %th{colspan: 4} Cônjuge
                %thead
                  %tr
                    %th Nome
                    %th CPF
                    %th RG
                    %th Sexo
                %tbody
                  %tr
                    %td= @spouse.name
                    %td= @spouse.cpf.present? ? @spouse.cpf : "Sem informação"
                    %td= @spouse.rg.present? ? "#{@spouse.rg} - #{@spouse.rg_org}/#{@spouse.rg_uf_id}" : "Sem informação"
                    %td= @spouse.gender.present? ? @spouse.gender : "Sem informação"
                %thead
                  %tr
                    %th Data de Nascimento
                    %th Renda
                    %th Condição Especial
                    %th CID
                %tbody
                  %tr
                    %td= @spouse.born.present? ? @spouse.born.strftime('%d/%m/%Y') : "Sem informação"
                    %td= @spouse.income.present? ? @spouse.income : "Sem informação"
                    %td= @spouse.special_condition.present? ? @spouse.special_condition.name : "Sem informação"
                    %td= @spouse.cid.present? ? @spouse.cid : "Sem informação"
            - if @dependents.present?
              - @dependents.each do |dependent|
                %table.table.table-striped.table-bordered
                  %thead
                    %tr
                      %th{colspan: 4}= dependent.kinship.name rescue "Sem informação"
                  %thead
                    %tr
                      %th Nome
                      %th CPF
                      %th RG
                      %th Sexo
                  %tbody
                    %tr
                      %td= dependent.name
                      %td= dependent.cpf.present? ? dependent.cpf : "Sem informação"
                      %td= dependent.rg.present? ? "#{dependent.rg} - #{dependent.rg_org}/#{dependent.rg_uf_id}" : "Sem informação"
                      %td= dependent.gender.present? ? dependent.gender : "Sem informação"
                  %thead
                    %tr
                      %th Data de Nascimento
                      %th Renda
                      %th Condição Especial
                      %th CID
                  %tbody
                    %tr
                      %td= dependent.born.present? ? dependent.born.strftime('%d/%m/%Y') : "Sem informação"
                      %td= dependent.income.present? ? dependent.income : "Sem informação"
                      %td= dependent.special_condition.present? ? dependent.special_condition.name : "Sem informação"
                      %td= dependent.cid.present? ? dependent.cid : "Sem informação"

engines/attendance/app/views/attendance/cadastres/detail.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            %h4
              %b
                Meu Cadastro
        .row
          .col-md-12
            %table.table.table-striped.table-bordered
              %thead
                %tr
                  %th Nome
                  %th CPF
                  %th RG
              %tbody
                %tr
                  %td= @cadastre.name
                  %td= @cadastre.cpf
                  %td= "#{@cadastre.rg} - #{@cadastre.rg_org}/#{@cadastre.rg_uf}"
              %thead
                %tr
                  %th Data de nascimento
                  %th Sexo
                  %th Local de Nascimento
              %tbody
                %tr
                  %td= @cadastre.born.strftime('%d/%m/%Y') rescue nil
                  %td= @cadastre.gender rescue nil
                  %td= @cadastre.place_birth
              %thead
                %tr
                  %th Chegada no DF
                  %th Estado Civil
                  %th Nome da Mãe
              %tbody
                %tr
                  %td= @cadastre.arrival_df.strftime('%d/%m/%Y') rescue nil
                  %td= @cadastre.civil_state.name rescue nil
                  %td= @cadastre.mother_name rescue nil
              %thead
                %tr
                  %th Condicão Especial
                  %th CID
                  %th Tipo de Condição Especial
              %tbody
                %tr
                  %td= @cadastre.special_condition.name rescue nil
                  %td= @cadastre.cid rescue nil
                  %td= @cadastre.special_condition_type.name rescue nil
              %thead
                %tr
                  %th NIS
                  %th Renda do Titular
                  %th Renda Familiar
              %tbody
                %tr
                  %td= @cadastre.nis rescue nil
                  %td= @cadastre.main_income rescue nil
                  %td= @cadastre.income rescue nil
              %thead
                %tr
                  %th{colspan: 3} Dados de Contato
              %thead
                %tr
                  %th Cidade
                  %th Endereço
                  %th Complemento do Endereço
              %tbody
                %tr
                  %td= @cadastre.city.name rescue nil
                  %td= @cadastre.address rescue nil
                  %td= @cadastre.address_complement rescue nil
              %thead
                %tr
                  %th{colspan: 3} Email
              %tbody
                %tr
                  %td{colspan: 3}= @cadastre.email rescue nil
              %thead
                %tr
                  %th Telefone
                  %th Telefone Opcional
                  %th Celular
              %tbody
                %tr
                  %td= @cadastre.telephone rescue nil
                  %td= @cadastre.telephone_optional rescue nil
                  %td= @cadastre.celphone rescue nil

engines/attendance/app/views/attendance/cadastres/edit.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            %h4
              %b Atualização de dados básicos
            %h4= link_to "Retonar para página anterior", new_ticket_path
        - if @ticket.closed?(@action)
          .row
            .col-md-12.text-center
              %p
                %h2
                  %b Dados #{@action.situation.name.pluralize}
        %hr/
        .row
          .col-md-12
            = render 'form'

engines/attendance/app/views/attendance/cadastres/index.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            %h4
              %b Meu cadastro
          
        %hr
        .row
          .col-md-12
            %table.table.table-striped.table-bordered
              %thead
                %tr
                  %th{colspan: 3}
                    %center
                      = current_cadastre.name.mb_chars.upcase
                %tr
                  %th{colspan: 3}
                    %center
                      = current_cadastre.presenter.current_situation_name
              %thead
                %tr
                  %th Lista
                  %th Faixa de Renda
                  %th Posição
              %tbody
                - current_cadastre.presenter.list.each do |list|
                  %tr
                    %td= I18n.t(list[0])
                    %td= list[1][0]
                    %td= list[2].present? ? list[2] : "Sem informação"
            %hr
            %table.table.table-striped.table-bordered
              %tbody
                %tr
                  %td.col-md-1
                    %span.fa.fa-user
                  %td= link_to "Meu cadastro", detail_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-users
                  %td= link_to " Meus dependentes", dependent_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-mail-forward
                  %td= link_to "Minhas Indicações", indication_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-area-chart
                  %td= link_to "Pontuações", pontuation_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-warning
                  %td= link_to "Ocorrências de IPTU", occurrence_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-building
                  %td= link_to " Minha entidade", entity_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-list
                  %td= link_to "Minhas situações", situation_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-key
                  %td= link_to "Endereço vínculado", address_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-file-text
                  %td= link_to "Processos / Documentos", document_cadastres_path
                %tr
                  %td.col-md-1
                    %span.fa.fa-calendar
                  %td= link_to "Agendamentos", schedule_cadastres_path