engines/document/config/routes.rb
Document::Engine.routes.draw do
  resources :allotments do
    resources :data_prints
    resources :data_print_files
  end

  get  'validate',   to: 'allotments#validate',   as: 'validate'
  post 'validation', to: 'allotments#validation', as: 'validation'
  get  'confirm',    to: 'allotments#confirm',    as: 'confirm'

  get 'document',         to: 'allotments#document',          as: 'document'

  get 'print_one',        to: 'allotments#print_one',        as: 'print_one'
  get 'print_two',        to: 'allotments#print_two',        as: 'print_two'
  get 'print_three',      to: 'allotments#print_three',      as: 'print_three'
  get 'print_correction', to: 'allotments#print_correction', as: 'print_correction'

end

engines/document/app/models/document/allotment.rb
module Document
  class Allotment < ApplicationRecord
    belongs_to :template
    belongs_to :staff

    has_many :data_prints
  end
end

engines/document/app/models/document/application_record.rb
module Document
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/document/app/models/document/validate.rb
module Document
  class Validate # :nodoc:
    include ActiveModel::Model
    attr_accessor :cpf, :document_date, :allotment_id, :id

    validate :authenticate?

    def authenticate?

      return errors.add(:cpf, 'Dados inválidos ou certidão não assinada.') unless self.cpf.present? && self.document_date.present?
      date =  Date.parse(self.document_date)
      new_cpf = self.cpf.gsub('-','').gsub('.','')

      @certificate = Core::Document::DataPrint.where(cpf: new_cpf, allotment_id: self.allotment_id).last
      @certi = Core::Document::DataPrint.where(cpf: new_cpf, id: self.allotment_id).last unless  @certificate.present?

      if @certificate.present? || @certi.present?
        allotment = @certificate.present? ? @certificate.allotment_id : @certi.allotment_id
      else
        errors.add(:cpf, 'Dados inválidos ou certidão não assinada.')
      end

      @allotment = Core::Document::Allotment.where('id = ? and data_document::date = ?', allotment, date).first

      if (@certificate.present? || @certi.present?) && @allotment.present?
        self.id = @certificate.present? ? @certificate.id : @certi.id
      else
        errors.add(:cpf, 'Dados inválidos ou certidão não assinada.')
      end
    end
  end
end

engines/document/app/controllers/document/allotments_controller.rb
require_dependency 'document/application_controller'

module Document
  class AllotmentsController < ApplicationController

    before_action :set_allotment, only: [:print_one, :print_two, :print_three, :print_correction]

    def validate
      order = params[:order].present? ? params[:order] : params[:o]
      if order.present? && !params[:r].present?
        redirect_to confirm_path(id: params[:id], order: order)
      else
        session[:id] = params[:id]
        @validate = Document::Validate.new
      end
    end

    def validation
      @validate = Document::Validate.new(set_params)
      if @validate.valid?
        redirect_to confirm_path(id: @validate.id)
      else
        render :validate
      end
    end

    def confirm
      if request.referer.nil?
        redirect_to validate_path(id: params[:id], order: params[:order], r: true)
      else
        @doc = Core::Document::DataPrint.find(params[:id])
        if @doc.allotment.main.present? || @doc.allotment.first.present? || @doc.allotment.second.present?
          order = params[:order].present? ? params[:order] : params[:o]
          case order
          when "1"
            @date =       "Em #{@doc.allotment.main_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
            @user       = "GILSON PARANHOS" rescue "Documento não assinado"
            @complement = "Diretor-Presidente da CODHAB/DF" if @doc.allotment.main.present?
          when "2"
            @date       = "Em #{@doc.allotment.first_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
            @user       = @doc.allotment.first.name rescue "Documento não assinado"
            @complement = @doc.allotment.first.job.name rescue nil
          when "3"
            @date       = "Em #{@doc.allotment.second_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
            @user       = @doc.allotment.second.name rescue "Documento não assinado"
            @complement = @doc.allotment.second.job.name + ' - ' + @doc.allotment.second.sector_current.name rescue nil
          when "4"
            @date       = "Em #{@doc.allotment.third_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
            @user       = @doc.allotment.third.name rescue "Documento não assinado"
            @complement = @doc.allotment.third.curriculum rescue nil
          when "5"
            @date       = "Em #{@doc.allotment.fourth_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
            @user       = @doc.allotment.fourth.name rescue "Documento não assinado"
            @complement = @doc.allotment.fourth.curriculum rescue nil
          when "6"
            @date       = "Em #{@doc.allotment.fifth_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
            @user       = @doc.allotment.fifth.name rescue "Documento não assinado"
            @complement = @doc.allotment.fifth.curriculum rescue nil
          end
          session.delete(:id)
        else
          @message = "O documento não foi assinado."
        end
      end
    end

    def print_one
      render layout: 'document'
    end

    def print_two
      render layout: 'document'
    end

    def print_three
      render layout: 'document'
    end


    def print_correction
      render layout: 'document'
    end

    def document
      @unit = Core::Address::Unit.where(id: params[:id], certificate: 'b').first
      @message = 'O documento não foi assinado.' unless @unit.present?
      render layout: 'application'
    end

    private

    def set_params
      params.require(:validate).permit(:cpf, :document_date, :allotment_id)
    end

    def set_allotment
      @doc = Core::Document::DataPrint.find(params[:id])
      @allotment = Core::Document::Allotment.find(@doc.allotment_id)
    end

  end
end

engines/document/app/controllers/document/application_controller.rb
module Document
  class ApplicationController  < ActionController::Base
    layout 'application'
    helper 'application'
  end
end

engines/document/app/helpers/document/application_helper.rb
module Document
  module ApplicationHelper
  end
end

engines/document/app/views/document/allotments/_form.html.haml
.col-md-12.col-md-offset-4
  = simple_form_for @validate, url: validation_path, method: :post do |f|
    = f.input :allotment_id, as: :hidden, input_html: { value: session[:id] }
    .row
      .col-md-2
        = f.label "CPF"
        = f.input :cpf, label: false, input_html: { class: 'cpf' }
    .row
      .col-md-2
        = f.label "Data do Documento"
        = f.input :document_date, label: false, input_html: {class: 'date'}
    .row
      .col-md-6
        = f.submit "Validar", class: 'btn btn-success'

engines/document/app/views/document/allotments/confirm.html.haml
.col-md-12
  .panel.panel-default
    .panel-body
      .row
        .col-md-12
          %h3
            %b Validação de Escrituras
      - if @doc.present? && !@message.present?
        .row
          .col-md-12
            %table.table.table-striped
              %tr
                %td{style: "width: 30%"}
                  %b Data do Documento
                %td{style: "width: 70%"}
                  %b Título
              %tr
                %td= @doc.allotment.data_document.strftime('%d/%m/%Y') rescue nil
                %td= @doc.allotment.template.title rescue nil
              %tr
                %td
                  %b Cidade
                %td
                  %b Endereço
              %tr
                %td= @doc.city.name rescue nil
                %td= @doc.complete_address rescue nil
              - if params[:order].present?
                %tr
                  %td
                    %b Expedido para:
                  %td
                    %b Assinado por
                %tr
                  %td
                    = @doc.name
                    %br
                    = "CPF: #{@doc.cpf.format_cpf}" rescue nil
                  %td
                    = @user rescue nil
                    %br
                    = @complement
                    %br
                    = @date
              - unless params[:order].present?
                - if @doc.allotment.main.present? && @doc.allotment.first.present? && @doc.allotment.second.present?
                  %tr
                    %td{colspan: 2}
                      %b Expedido para:
                  %tr
                    %td{colspan: 2}
                      = @doc.name
                      %br
                      = "CPF: #{@doc.cpf.format_cpf}" rescue nil
                  %tr
                    %td{colspan: 2}
                      %b Assinado por:
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.main_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = "GILSON PARANHOS" rescue "Documento não assinado"
                      %br
                      = "Diretor-Presidente da CODHAB/DF" if @doc.allotment.main.present?
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.first_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.first.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.first.job.name + ' - ' + @doc.allotment.first.sector_current.name rescue nil                  
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.second_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.second.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.second.job.name + ' - ' + @doc.allotment.second.sector_current.name rescue nil
                  - if @doc.allotment.terracap
                    %tr
                      %td{colspan: 2}
                        = "Em #{@doc.allotment.third_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                        %br
                        = @doc.allotment.third.name rescue "Documento não assinado"
                        %br
                        = @doc.allotment.third.curriculum rescue nil
                    %tr
                      %td{colspan: 2}
                        = "Em #{@doc.allotment.fourth_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                        %br
                        = @doc.allotment.fourth.name rescue "Documento não assinado"
                        %br
                        = @doc.allotment.fourth.curriculum rescue nil
                    %tr
                      %td{colspan: 2}
                        = "Em #{@doc.allotment.fifth_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                        %br
                        = @doc.allotment.fifth.name rescue "Documento não assinado"
                        %br
                        = @doc.allotment.fifth.curriculum rescue nil
      - else
        .alert.alert-warning
          = @message

engines/document/app/views/document/allotments/document.html.haml
.col-md-12
  .panel.panel-default
    .panel-body
      .row
        .col-md-12
          %h3
            %b Validação de Escrituras
      - if @unit.present?
        .row
          .col-md-12
            %table.table.table-striped
              %tr
                %td{style: "width: 30%"}
                  %b Data do Documento
                %td{style: "width: 70%"}
                  %b Título
              %tr
                %td 14/12/2017
                %td TERMO DE OCUPAÇÃO DE USO PRECÁRIO DE IMÓVEL PÚBLICO A TÍTULO GRATUITO
              %tr
                %td
                  %b Cidade
                %td
                  %b Endereço
              %tr
                %td= @unit.city.name rescue nil
                %td= @unit.complete_address rescue nil
              - if @unit.current_candidate.present?
                %tr
                  %td{colspan: 2}
                    %b Expedido para:
                %tr
                  %td{colspan: 2}
                    = @unit.current_candidate.name rescue nil
                    %br
                    = "CPF: #{@unit.current_candidate.cpf.format_cpf}" rescue nil
                
                - if params[:f].present?
                  %tr         
                    %td{colspan: 2}
                      %b Assinado por:
                  %tr
                    %td{colspan: 2}
                      = "Em 10/07/2019" rescue nil
                      %br
                      WELLINGTON LUIZ DE SOUZA SILVA
                      %br
                      Diretor-Presidente da CODHAB/DF
                  %tr
                    %td{colspan: 2}
                      = "Em 10/07/2019"
                      %br
                      MARCUS JOSE DA CRUZ PALOMO
                      %br
                      DIRETOR - DIRETORIA IMOBILIÁRIA - DIMOB
                  %tr
                    %td{colspan: 2}
                      = "Em 10/07/2019" rescue nil
                      %br
                      PATRICIA SILVA DO NASCIMENTO
                      %br
                      ASSESSOR PLENO - GERÊNCIA DE CADASTRO - DIMOB/GECAD                
                - else
                  - unless params[:o].present?
                    %tr
                      %td{colspan: 2}
                        %b Assinado por:
                    %tr
                      %td{colspan: 2}
                        = "Em 14/12/2017" rescue nil
                        %br
                        GILSON PARANHOS
                        %br
                        Diretor-Presidente da CODHAB/DF
                    %tr
                      %td{colspan: 2}
                        = "Em 14/12/2017"
                        %br
                        RAFAEL VENUTO GONÇALVES SOBENES
                        %br
                        GERENTE - GERÊNCIA DE MOBILIZAÇÃO SOCIAL - GEMOB
                    %tr
                      %td{colspan: 2}
                        = "Em 14/12/2017" rescue nil
                        %br
                        VICTOR RAMON DE PAIVA FONSECA
                        %br
                        Assessor Pleno - GERÊNCIA DE MOBILIZAÇÃO SOCIAL - GEMOB
                  - case params[:o]
                  - when "1"
                    %tr
                      %td{colspan: 2}
                        %b Assinado por:
                    %tr
                      %td{colspan: 2}
                        = "Em 14/12/2017" rescue nil
                        %br
                        GILSON PARANHOS
                        %br
                        Diretor-Presidente da CODHAB/DF
                  - when "2"
                    %tr
                      %td{colspan: 2}
                        %b Assinado por:
                    %tr
                      %td{colspan: 2}
                        = "Em 14/12/2017"
                        %br
                        RAFAEL VENUTO GONÇALVES SOBENES
                        %br
                        GERENTE - GERÊNCIA DE MOBILIZAÇÃO SOCIAL - GEMOB
                  - when "3"
                    %tr
                      %td{colspan: 2}
                        %b Assinado por:
                    %tr
                      %td{colspan: 2}
                        = "Em 14/12/2017" rescue nil
                        %br
                        VICTOR RAMON DE PAIVA FONSECA
                        %br
                        Assessor Pleno - GERÊNCIA DE MOBILIZAÇÃO SOCIAL - GEMOB
      - else
        .alert.alert-warning
          = @message

engines/document/app/views/document/allotments/print_correction.html.haml
- @doc = Core::Document::DataPrintPresenter.new(@doc)
%page{:size => "A4"}
  .container{style: "font-size: #{@allotment.template.text_font_size rescue nil}pt"}
    .lateral-margins.spacing{style: "text-align: justify; font-size: #{@allotment.template.head_font_size rescue nil}pt; important!"}
      - if @doc.cancelled == true
        = image_tag('/extranet/images/cancelled.png', width: '500', style: 'position: absolute; top: 200px; margin-left: 150px; opacity: 0.8' )
      %label
        %b
          = @allotment.template.title.html_safe rescue "Preencher dados"
      %br
      %br
      .data-candidate
        = @doc.write_document(@allotment.template.header).html_safe
      %br
    .content.lateral-margins.spacing
      = @doc.correction.html_safe
      %br
      %br
      .div-center
        %b
          = "Brasília, #{@allotment.data_document.day} de #{I18n.t("date.month_names")[@allotment.data_document.month]} de #{@allotment.data_document.year}"
      %br
      %br
      .div-center
        _________________________________________________
        %br
        =@allotment.template.main_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
        %br
        =@allotment.template.main_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
      %br
      .div-center
        _________________________________________________
        %br
        = @doc.name rescue "<span>COMPLETAR DADOS</span>".html_safe
        %br
        Donatário(a)
      - if @doc.spouse_name.present?
        .div-center
          _________________________________________________
          %br
          = @doc.spouse_name rescue "<span>COMPLETAR DADOS</span>".html_safe
          %br
          Donatário(a)
      - if @allotment.template.first_signature.present? || @allotment.template.second_signature.present?
        .div-center
          %h4 Testemunhas:
        .content.lateral-margins.spacing
          %table{border: 0, style: "width: 550px; margin: 0 auto"}
            %tr
              %td
                %center
                  __________________________________________
                  %br
                  = @allotment.template.first_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
                  %br
                  = @allotment.template.first_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
              - if @allotment.template.second_signature.present?
                %td
                  %center
                    ___________________________________________
                    %br
                    = @allotment.template.second_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
                    %br
                    = @allotment.template.second_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
      .div-center
        = image_tag ::PrintingQrcodeService.generate!("http://www.codhab.df.gov.br/documento/print_correction?id=#{@doc.id}")
        %br
        %a{style: "font-size: 9px"}= Digest::MD5.hexdigest @doc.id.to_s
  %div{:style => "page-break-after:always"}

engines/document/app/views/document/allotments/print_one.html.haml
<<<<<<< HEAD
- if @allotment.present? && @allotment.data_prints.where(status: true).present?
  - @allotment.data_prints.where(status: true).each do |allotment|
    - @doc = allotment
    - @doc = Core::Document::DataPrintPresenter.new(@doc)
    %page{:size => "A4"}
      .container{style: "font-size: 9pt"}
        .lateral-margins.spacing{style: 'text-align: justify; font-size: 8pt; important!'}
          %label
            %b
              = @allotment.template.title.html_safe rescue "Preencher dados"
          %br
          %br
          .data-candidate
            = @doc.write_document(@allotment.template.header).html_safe
          %br
        .content.lateral-margins.spacing
          = @doc.write_document(@allotment.template.page_one).html_safe rescue "Preencher dados"
          %br
          %br
          .div-center
            %b
              = "Brasília, #{@allotment.data_document.day} de #{I18n.t("date.month_names")[@allotment.data_document.month]} de #{@allotment.data_document.year}"
          %br
          %br
          .div-center
            _________________________________________________
            %br
            =@allotment.template.main_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
            %br
            =@allotment.template.main_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
          %br
          .div-center
            _________________________________________________
            %br
            = @doc.name rescue "<span>COMPLETAR DADOS</span>".html_safe
            %br
            Donatário(a)
          - if @doc.spouse_name.present?
            .div-center
              _________________________________________________
              %br
              = @doc.spouse_name rescue "<span>COMPLETAR DADOS</span>".html_safe
              %br
              Donatário(a)
          - if @allotment.template.first_signature.present? || @allotment.template.second_signature.present?
            .div-center
              %h4 Testemunhas:
            .content.lateral-margins.spacing
              %table{border: 0, style: "width: 550px; margin: 0 auto"}
                %tr
                  %td
                    %center
                      __________________________________________
                      %br
                      = @allotment.template.first_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
                      %br
                      = @allotment.template.first_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
                  - if @allotment.template.second_signature.present?
                    %td
                      %center
                        ___________________________________________
                        %br
                        = @allotment.template.second_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
                        %br
                        = @allotment.template.second_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
          .div-center
            = image_tag ::PrintingQrcodeService.generate!("http://www.codhab.df.gov.br/documento/print_one?id=#{@doc.id}")
            %br
            %a{style: "font-size: 9px"}= Digest::MD5.hexdigest @doc.id.to_s
      %div{:style => "page-break-after:always"}
=======
- if @doc.present?
  - @doc = Core::Document::DataPrintPresenter.new(@doc)
  %page{:size => "A4"}
    .container{style: "font-size: 9pt"}
      .lateral-margins.spacing{style: 'text-align: justify; font-size: 8pt; important!'}
        - if @doc.cancelled == true
          = image_tag('/portal/images/cancelled.png', width: '500', style: 'position: absolute; top: 200px; margin-left: 150px; opacity: 0.8' )
        %label
          %b
            = @allotment.template.title.html_safe rescue "Preencher dados"
        %br
        %br
        .data-candidate
          = @doc.write_document(@allotment.template.header).html_safe
        %br
      .content.lateral-margins.spacing
        = @doc.write_document(@allotment.template.page_one).html_safe rescue "Preencher dados"
        %br
        %br
        .div-center
          %b
            = "Brasília, #{@allotment.data_document.day} de #{I18n.t("date.month_names")[@allotment.data_document.month]} de #{@allotment.data_document.year}"
        %br
        %br
        .div-center
          _________________________________________________
          %br
          =@allotment.template.main_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
          %br
          =@allotment.template.main_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
        %br
        .div-center
          _________________________________________________
          %br
          = @doc.name rescue "<span>COMPLETAR DADOS</span>".html_safe
          %br
          Donatário(a)
        - if @doc.spouse_name.present?
          .div-center
            _________________________________________________
            %br
            = @doc.spouse_name rescue "<span>COMPLETAR DADOS</span>".html_safe
            %br
            Donatário(a)
        - if @allotment.template.first_signature.present? || @allotment.template.second_signature.present?
          .div-center
            %h4 Testemunhas:
          .content.lateral-margins.spacing
            %table{border: 0, style: "width: 550px; margin: 0 auto"}
              %tr
                %td
                  %center
                    __________________________________________
                    %br
                    = @allotment.template.first_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
                    %br
                    = @allotment.template.first_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
                - if @allotment.template.second_signature.present?
                  %td
                    %center
                      ___________________________________________
                      %br
                      = @allotment.template.second_signature rescue "<span>COMPLETAR DADOS</span>".html_safe
                      %br
                      = @allotment.template.second_complement rescue "<span>COMPLETAR DADOS</span>".html_safe
        .div-center
          = image_tag ::PrintingQrcodeService.generate!("http://www.codhab.df.gov.br/documento/print_one?id=#{@doc.id}")
          %br
          %a{style: "font-size: 9px"}= Digest::MD5.hexdigest @doc.id.to_s
    %div{:style => "page-break-after:always"}
>>>>>>> 4f06670ec20d30af4d9852030d8e1470f56a0bb5

engines/document/app/views/document/allotments/validate.html.haml
.row
  .col-md-12.box
    .panel.panel-default
      .panel-body
        .row
          .col-md-6.col-md-offset-3
            %h1{style: "text-align: center !important"}
              %b Validação em dois passos
              %br/
              %small
                Preencha os campos abaixo para validar o documento
        %hr/
        .row
          .col-md-12
            %br/
            %br/
            = render 'form'

engines/document/app/views/document/allotments/validate1.html.haml
.col-md-12
  .panel.panel-default
    .panel-body
      .row
        .col-md-12
          %h3
            %b Validação de Escrituras
      - if @doc.present? && !@message.present?
        .row
          .col-md-12
            %table.table.table-striped
              %tr
                %td{style: "width: 30%"}
                  %b Data do Documento
                %td{style: "width: 70%"}
                  %b Título
              %tr
                %td= @doc.allotment.data_document.strftime('%d/%m/%Y') rescue nil
                %td= @doc.allotment.template.title rescue nil
              %tr
                %td
                  %b Cidade
                %td
                  %b Endereço
              %tr
                %td= @doc.city.name rescue nil
                %td= @doc.complete_address rescue nil
              - if params[:order].present?
                %tr
                  %td
                    %b Expedido para:
                  %td
                    %b Assinado por
                %tr
                  %td
                    = @doc.name
                    %br
                    = "CPF: #{@doc.cpf.format_cpf}" rescue nil
                  %td
                    = @user rescue nil
                    %br
                    = @complement
                    %br
                    = @date
              - unless params[:order].present?
                - if @doc.allotment.main.present? && @doc.allotment.first.present? && @doc.allotment.second.present?
                  %tr
                    %td{colspan: 2}
                      %b Expedido para:
                  %tr
                    %td{colspan: 2}
                      = @doc.name
                      %br
                      = "CPF: #{@doc.cpf.format_cpf}" rescue nil
                  %tr
                    %td{colspan: 2}
                      %b Assinado por:
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.main_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = "GILSON PARANHOS" rescue "Documento não assinado"
                      %br
                      = "Diretor-Presidente da CODHAB/DF" if @doc.allotment.main.present?
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.first_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.first.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.first.job.name + ' - ' + @doc.allotment.first.sector_current.name rescue nil
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.second_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.second.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.second.job.name + ' - ' + @doc.allotment.second.sector_current.name rescue nil
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.third_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.third.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.third.curriculum rescue nil
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.fourth_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.fourth.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.fourth.curriculum rescue nil
                  %tr
                    %td{colspan: 2}
                      = "Em #{@doc.allotment.fifth_authenticate_date.strftime('%d/%m/%Y - %H:%M:%S')}" rescue nil
                      %br
                      = @doc.allotment.fifth.name rescue "Documento não assinado"
                      %br
                      = @doc.allotment.fifth.curriculum rescue nil
      - else
        .alert.alert-warning
          = @message