engines/regularization/config/routes.rb
Regularization::Engine.routes.draw do
  root 'home#index'

  get   '/pesquisa-cpf',  to: 'cadastres#find_candidate', as: 'find_candidate'
  post  '/pesquisa-cpf',  to: 'cadastres#show_candidate', as: 'show_candidate'

  resources :lists, path: 'listas'
  resources :requests, path: 'requerimento'
  resources :cadastres, path: 'cadastro'
  resources :solicitations, path: 'solicitacoes'

=begin
  resources :requeriments, path: 'requerimentos' do
    collection do
      get   '/address', path: 'endereco', to: 'requeriments#new_address', as: 'new_address'
      post  '/address', path: 'endereco', to: 'requeriments#set_address', as: 'set_address'
      get   '/success', path: 'sucesso',  to: 'requeriments#success',     as: 'success'
    end
  end
=end

  resources :mestre_darmas_regularizations, path: 'mestre-darmas'
  resources :mestre_darmas_regularization_sessions, path: 'mestre-darmas-acesso'
  resources :mestre_darmas_regularization_cadastres, path: 'mestre-darmas-cadastros'

  resources :itapoa_regularizations, path: 'regularizacao-itapoa' do
    collection do
      resources :sessions, path: 'acesso', controller: :itapoa_regularization_sessions, as: :itapoa_regularization_sessions
      get 'get_iptu_code', as: :get_iptu_code
      
      post 'set_iptu'
    end

    get 'update_situation'

  end

  resources :vitoria_regularizations, path: 'nova-vitoria' do
    collection do
      resources :sessions, path: 'acesso', controller: :vitoria_regularization_sessions, as: :vitoria_regularization_sessions
      get 'get_iptu_code', as: :get_iptu_code
      
      post 'set_iptu'
    end

    get 'update_situation'

  end  

  namespace :candidate, path: 'candidato' do
=begin
    resources :requeriments,  path: 'requerimentos' do
      collection do
        get '/verification',  path: 'verificacao', to: 'requeriments#verification', as: 'verification'
        post '/verification', path: 'verificacao', to: 'requeriments#validate_verification', as: 'validate_verification'
      end
    end
=end

    resources :schedules, path: 'agendamentos' do
      collection do
        get '/verification', path: 'verificacao', to: 'schedules#verification', as: 'verification'
      end
    end


  end



end

engines/regularization/app/models/regularization/address.rb
module Regularization
  class Address
    include ActiveModel::Model

    attr_accessor :city, :block, :group, :unit, :id

    validates_presence_of :city, :block, :group, :unit, :id

  end
end

engines/regularization/app/models/regularization/find.rb
module Regularization
  class Find
    include ActiveModel::Model

    attr_accessor :cpf

    validates :cpf, cpf: true, presence: true
    validate :cpf_exists?

    private

    def cpf_exists?
      errors.add(:cpf, "CPF não encontrado") unless ::Candidate::Cadastre.regularization.where(cpf: self.cpf).present?
    end
  end
end

engines/regularization/app/models/regularization/itapoa_regularization_session.rb
module Regularization
  class ItapoaRegularizationSession
    include ActiveModel::Model

    attr_accessor :name, :cpf, :born, :itapoa_regularization_id

    validates :name, :born, presence: true
    validates :cpf, cpf: true, presence: true
    validate  :validate_cpf

    def authenticate(session)
      return false unless valid?

      session[:itapoa_regularization_id] = self.itapoa_regularization_id
      
      true
    end

    private

    def validate_cpf
      itapoa_regularization = Regularization::ItapoaRegularization.find_by(cpf: true)

      if itapoa_regularization.nil?
        errors.add(:cpf, 'informando não possui solicitação.')
      else
        self.itapoa_regularization_id = itapoa_regularization.id 

        if self.born.present? && (itapoa_regularization.born != Date.parse(self.born))
          errors.add(:born, 'não é igual a informada na solicitação')
        end

        name_upcase = self.name.to_s.mb_chars.upcase
        itapoa_regularization_name = itapoa_regularization.name.to_s.mb_chars.upcase

        if name_upcase.similiar(itapoa_regularization_name) < 80
          errors.add(:name, 'não é igual ao informado na solicitação')
        end
      end
    end
  end
end

engines/regularization/app/models/regularization/mestre_darmas_regularization_session.rb
module Regularization
  class MestreDarmasRegularizationSession
    include ActiveModel::Model
  
    attr_accessor :username, :password, :id, :mestre_darmas_user

    validates :username, :password, presence: true
    validate :user_authenticate!

    def authenticate(session)
      return false if invalid?

      session[:mestre_darmas_user_id] = @mestre_darmas_user.id

      true
    end

    private

    def user_authenticate!
      @mestre_darmas_user = ::Candidate::ExternalAttendance::User.find_by(cpf: self.username)
      
      if @mestre_darmas_user.nil? || (::BCrypt::Password.new(@mestre_darmas_user.password_digest) != self.password)
        errors.add(:username, "ou senha não conferem")
      end
    end

  end
end

engines/regularization/app/models/regularization/requeriment_verification.rb
module Regularization
  class RequerimentVerification
    include ActiveModel::Model

    attr_accessor :cpf, :born, :id, :requeriment


    validates :cpf, cpf: true, presence: true
    validates_date :born, presence: true

    validate :candidate_exists?

    def first
      self.requeriment
    end

    private

    def candidate_exists?
      if self.cpf.present? && self.born.present?
        self.requeriment = Regularization::Requeriment.where(cpf: self.cpf, born: self.born).first
        errors.add(:cpf, 'não existem requerimentos vínculado aos dados informados') if !self.requeriment.present?
      end
    end
  end
end

engines/regularization/app/controllers/regularization/application_controller.rb
module Regularization
  class ApplicationController < ActionController::Base
    layout 'application'
    helper 'application'
    
    helper_method :mobile_device?
    
    private
    
    def mobile_device?
      if session[:mobile_param]
        session[:mobile_param] == "1"
      else
        request.user_agent =~ /Mobile|webOS/
      end
    end

  end
end

engines/regularization/app/controllers/regularization/cadastres_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  class CadastresController < ApplicationController
    before_action :set_http_support

    def show
      #@candidate = ::Candidate::Cadastre.regularization.find_by_cpf(params[:id])
      @candidate = @http.get("/candidato/cadastros/#{params[:id]}.json")

    end

    def find_candidate
      @candidate = Candidate::Search.new
    end

    def show_candidate
      @candidate = Candidate::Search.new(set_search_params)

      if @candidate.valid?
        redirect_to cadastre_path(@candidate.cadastre_id)
      else
        render action: :find_candidate
      end

    end

    private

    def set_search_params
      params.require(:search).permit(:cpf)
    end

    def set_http_support
      server  = Rails.env.development? ? "http://localhost:3001" : "http://extranet.codhab.df.gov.br"
      @http   = HttpSupport.new(server, 'eed6a8780692be1675b1bd0f386ca8b0')
    end

  end
end

engines/regularization/app/controllers/regularization/candidate/requeriments_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  module Candidate
    class RequerimentsController < ApplicationController
      before_action :validate_candidate!, except: [:verification, :validate_verification]
      before_action :set_requeriments, only: [:index, :show]

      def verification
        session[:candidate_cpf] = nil
        @requeriment = RequerimentVerification.new
      end

      def validate_verification
        @requeriment = RequerimentVerification.new(set_requeriment_params)

        if @requeriment.valid?
          session[:candidate_cpf] = @requeriment.first.cpf
          flash[:success] = t :success
          redirect_to action: 'index'
        else
          flash[:danger] = t :danger
          render action: 'verification'
        end
      end

      def index
      end

      def show
        @requeriment = @requeriments.find(params[:id])
      end

      private

      def set_requeriments
        @requeriments = Regularization::Requeriment.where(cpf: session[:candidate_cpf])
      end

      def validate_candidate!
        if !session[:candidate_cpf].present?
          redirect_to verification_candidate_requeriments_path
        end
      end

      def set_requeriment_params
        params.require(:requeriment_verification).permit(:cpf, :born)
      end
    end
  end
end

engines/regularization/app/controllers/regularization/candidate/schedules_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  module Candidate
    class SchedulesController < ApplicationController
      def index
      end
    end
  end
end

engines/regularization/app/controllers/regularization/home_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  class HomeController < ApplicationController

    def index
    end

  end
end

engines/regularization/app/controllers/regularization/itapoa_regularization_sessions_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  class ItapoaRegularizationSessionsController < ApplicationController
  
    def index
      redirect_to action: :new
    end 

    def new
      @session = Regularization::ItapoaRegularizationSession.new
    end
    
    def create
      @session = Regularization::ItapoaRegularizationSession.new(set_params)

      if @session.authenticate(session)
        redirect_to regularization.itapoa_regularization_path(@session.itapoa_regularization_id)
      else
        render action: :new
      end
    end

    private

    def set_params
      params.require(:itapoa_regularization_session).permit(:name, :cpf, :born)
    end

  end
end

engines/regularization/app/controllers/regularization/itapoa_regularizations_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  class ItapoaRegularizationsController < ApplicationController 

    def index
      session[:itapoa_regularization_id] = nil
      session[:unit_id] = nil
    end

    def new
      @itapoa_regularization = Regularization::ItapoaRegularization.new
    end
    
    def create
      @itapoa_regularization = Regularization::ItapoaRegularization.new(set_params)
      @itapoa_regularization.unit_id = session[:unit_id]
      
      if @itapoa_regularization.save
        session[:itapoa_regularization_id] = @itapoa_regularization.id
        redirect_to regularization.edit_itapoa_regularization_path(@itapoa_regularization)
      else
        render action: :new
      end
    end
    
    def show
      @itapoa_regularization = Regularization::ItapoaRegularization.where(cpf: params[:cpf])
    end
    
    def edit
      @itapoa_regularization = Regularization::ItapoaRegularization.find(session[:itapoa_regularization_id])
    end
    
    def update
      @itapoa_regularization = Regularization::ItapoaRegularization.find(session[:itapoa_regularization_id])
      
      if @itapoa_regularization.candidato? && @itapoa_regularization.update(set_edit_params)
        render action: :edit
      else
        render action: :edit
      end
      
      
    end
    
    def update_situation
      @itapoa_regularization = Regularization::ItapoaRegularization.find(session[:itapoa_regularization_id])
      @itapoa_regularization.update(situation_id: 2) 

      render action: :edit
    end
    
    def get_iptu_code
    end
    
    def set_iptu
      @itapoa_regularization = Regularization::ItapoaRegularization.new(set_params_iptu)
      @itapoa_regularization.iptu_valid?(session)

      render action: :new
    end

    private

    def set_edit_params
      params.require(:itapoa_regularization)
        .permit(:name, :rg, :naturality, 
                :income, :habitation_type_id, :spouse_cpf, 
                :spouse_rg, :spouse_name, :spouse_job, 
                :spouse_income, :phone, :email, :civil_state_id,
                :no_iptu_code, :born, :declaration_occupation, 
                :declaration_negative, :declaration_descriptive, :declaration_pacific, 
                :declaration_unit_area, :declaration_spouse_pacific, :declaration_informal_activity, 
                :declaration_informal_activity_value, :declaration_spouse_informal_activity, 
                :declaration_spouse_informal_activity_value, :terms_use,
                :complete_address, :spouse_born, :unit_characterist, :unit_characterist_occupation, 
                :unit_characterist_edification, :unit_characterist_room, :unit_characterist_dweller, 
                :unit_characterist_piped_water, :unit_characterist_electricity, :unit_characterist_sewer,
                :document_rg, 
                :phone_secondary,
                :document_cpf, 
                :document_civil_state, 
                :document_income, 
                :document_spouse_income, 
                :document_spouse_rg, 
                :document_spouse_cpf, 
                :document_occupation_time, 
                :photo_unit_front, 
                :photo_unit_inside_one, 
                :photo_unit_inside_two, 
                :document_address, 
                :document_iptu )     
    end

    def set_params_iptu
      params.require(:itapoa_regularization)
        .permit(:iptu_code)
    end

    def set_params
      params.require(:itapoa_regularization)
        .permit(:name, :iptu_code, :cpf, :rg, :naturality, 
                :income, :habitation_type_id, :spouse_cpf, 
                :spouse_rg, :spouse_name, :spouse_job, :phone_secondary,
                :spouse_income, :phone, :email, :civil_state_id,
                :no_iptu_code, :born, :declaration_occupation, 
                :declaration_negative, :declaration_descriptive, :declaration_pacific, 
                :declaration_unit_area, :declaration_spouse_pacific, :declaration_informal_activity, 
                :declaration_informal_activity_value, :declaration_spouse_informal_activity, 
                :declaration_spouse_informal_activity_value, :terms_use,
                :complete_address, :spouse_born, :unit_characterist, :unit_characterist_occupation, 
                :unit_characterist_edification, :unit_characterist_room, :unit_characterist_dweller, 
                :unit_characterist_piped_water, :unit_characterist_electricity,
                :unit_characterist_sewer)
  
    end

  end
end

engines/regularization/app/controllers/regularization/lists_controller.rb
require_dependency 'regularization/application_controller'

module Regularization
  class ListsController < ApplicationController
    before_action :set_list, only: [:show]

    has_scope :cpf
    def index
      @lists = Candidate::List.regularization
    end

    def show
      @geral = "#{@list.view_target}".constantize.where("#{@list.condition_sql}")
      @candidates = apply_scopes(@geral).paginate(:page => params[:page], :per_page => 20)
    end

    private

    def set_list
      begin
        @list = ::Candidate::List.portal.friendly.find(params[:id])
      rescue
        redirect_to '/404'
      end
    end

  end
end

engines/regularization/app/controllers/regularization/mestre_darmas_regularization_cadastres_controller.rb
module Regularization
  class MestreDarmasRegularizationCadastresController < ApplicationController
    before_action :mestre_darmas_user_authenticate!
    helper_method :mestre_darmas_current_user
    def index
      @solicitations = ::Regularization::MestreDarmasRegularization.all.order(created_at: :asc)
    end 
    
    def show
      @solicitation = ::Regularization::MestreDarmasRegularization.find(params[:id])
    end


    
    private

    def mestre_darmas_user_authenticate!
      if mestre_darmas_current_user.nil?
        redirect_to regularization.mestre_darmas_regularization_sessions_path if controller_name != 'mestre_darmas_sessions'
      end  
    end

    def mestre_darmas_current_user 
      ::Candidate::ExternalAttendance::User.find_by(id: session[:mestre_darmas_user_id])
    end

  end
end

engines/regularization/app/controllers/regularization/mestre_darmas_regularization_sessions_controller.rb
module Regularization
  class MestreDarmasRegularizationSessionsController < ApplicationController
  
    def index
      redirect_to action: :new
    end

    def new
      @mestre_darmas_regularization_session = ::Regularization::MestreDarmasRegularizationSession.new
    end
    
    def create
      @mestre_darmas_regularization_session = ::Regularization::MestreDarmasRegularizationSession.new(set_params)
      
      if @mestre_darmas_regularization_session.authenticate(session)
        redirect_to regularization.mestre_darmas_regularization_cadastres_path
      else
        render action: :new
      end
    end

    def destroy
      session[:mestre_darmas_user_id] = nil

      redirect_to regularization.mestre_darmas_regularization_sessions_path
    end

    private

    def set_params
      params.require(:mestre_darmas_regularization_session).permit(:username,:password)
    end

  end
end

engines/regularization/app/views/regularization/requests/create.html.haml
.row
  .col-md-12.box
    .panel.panel-default
      .panel-body
        %div{style: "text-align: center"}
          %h2.ui.center.aligned.icon.header
            %b Parabéns! Seu recurso foi enviado com sucesso!
            %br/
            %br/
            %p 
              Protocolo de autenticação da operação: 
              %b #{@request.request.id}#{Date.current.year}
%br/
%br/
%br/

engines/regularization/app/views/regularization/requests/new.html.haml
.row
  .col-md-12.box
    .panel.panel-default
      .panel-heading.green
        .row
          .col-md-12
            %h1
              %b Novo recurso
      .panel-body
        = simple_form_for @request, url: requests_path, method: 'post' do |f|
          .row
            .col-md-3
              = f.input :city_id, label: 'Cidade', as: :select, collection: Address::City.where(id: 821), include_blank: 'Selecione...', input_html: {id: 'city_id'}
            .col-md-3
              = f.input :block,label: 'Quadra', as: :select, collection: f.object.city_id.present? ? Address::Unit.where(city_id: f.object.city_id).order('block ASC').uniq.pluck(:block) : {}, include_blank: 'Selecione...', input_html: {id: 'block',  value: f.object.block.present? ? f.object.block : nil}
            .col-md-3
              = f.input :group,label: 'Conjunto', as: :select, collection: f.object.block.present? ? Address::Unit.where(city_id: f.object.city_id, block: f.object.block).select(:group).distinct.order('"group" ASC') : {}, label_method: :group, value_method: :group, include_blank: 'Selecione...', input_html: {id: 'group',  value: f.object.group.present? ? f.object.group : nil}
            .col-md-3
              = f.input :unit, label: 'Unidade', as: :select, collection: f.object.group.present? ? Address::Unit.where(city_id: f.object.city_id, block: f.object.block, group: f.object.group).select(:id, :unit).distinct.order('unit ASC') : {},label_method: :unit, value_method: :id,  include_blank: 'Selecione...', input_html: {id: 'unit',  value: f.object.unit.present? ? f.object.unit : nil}

          .row
            .col-md-8
              = f.input :name,  label: 'Nome', placeholder:  'Informe seu nome'
            .col-md-4
              = f.input :cpf, label: 'Cpf', input_html:{ class: 'cpf'}

          .row
            .col-md-4
              = f.input :telephone, label: 'Telefone', placeholder:  'Informe seu telefone'
            .col-md-4
              = f.input :telephone_optional, label: 'Telefone(opcional)', placeholder:  'Informe outro telefone'
            .col-md-4
              = f.input :email,  label: 'E-mail', placeholder:  'Informe seu e-mail'
            

          .row
            .col-md-12
              = f.input :description,as: :text, label: 'Recurso', input_html: { rows: 5, cols: 20}, placeholder:  'Infome seu recurso'
              
          .row
            .col-md-3
              = f.input :file, as: :file, label: 'Arquivo'
          
          %hr/
          .row
            .col-md-12
              = f.submit "Enviar recurso", class: "btn btn-success"


:javascript
          
  $(document).ready(function() {

    $("#city_id").on('change', function(){
      city = $(this).val();
      
      $.getJSON("/regularizacao/requerimento.json?by_city=" + city , function(data) {

        html = "<option value>selecione...</option>"

        for(var i = 0; i < data.blocks.length; i++) {
          html += "<option value='"+data.blocks[i].value+"'>"+data.blocks[i].value+"</option>"
        }
        console.log(html)
        $("#block").html(html)

      });
    });

    $("#block").on('change', function(){
      block = $(this).val();
      
      $.getJSON("/regularizacao/requerimento.json?by_city=" + $("#city_id").val() + "&by_block=" + block, function(data) {

        html = "<option value>selecione...</option>"

        for(var i = 0; i < data.groups.length; i++) {
          html += "<option value='"+data.groups[i].value.group+"'>"+data.groups[i].value.group+"</option>"
        }
        console.log(html)
        $("#group").html(html)

      });
    });

    $("#group").on('change', function(){
      group = $(this).val();
      
      $.getJSON("/regularizacao/requerimento.json?by_city=" + $("#city_id").val() + "&by_block=" + $("#block").val() + "&by_group=" + group , function(data) {

        html = "<option value>selecione...</option>"

        for(var i = 0; i < data.units.length; i++) {
          html += "<option value='"+data.units[i].value.id+"'>"+data.units[i].value.unit+"</option>"
        }
        console.log(html)

        $("#unit").html(html)

      });
    });

  });